### ISSUE TITLE
Sitemap Re-Implementation

### ISSUE THREAD

**Issue by glcheetham** [webuyanybike/webuyanybike#17]
Main issues to fix:
- [x] Sitemap not giving canonical link to pages (#14)
- [x] Sitemap showing non-https version of links (also #14)
- [x] Add redirect for sitemap.xml in Umbraco configuration (related to #18)
